recipe: default.v1
assistant_id: chefbot
language: pt

pipeline:
- name: WhitespaceTokenizer

#- name: DIETClassifier
 # epochs: 100
  #constrain_similarities: true

- name: CompactLLMCommandGenerator

  llm: 
    model_group: gemini-llm

  flow_retrieval: 
    embeddings:
      model_group: google-embeddings

policies:
  - name: FlowPolicy
    embeddings:
      model_group: google-embeddings
  
  - name: IntentlessPolicy
    llm:
      model_group: gemini-llm
    embeddings:
      model_group: google-embeddings

  - name: TEDPolicy
    max_history: 10
    epochs: 100
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "utter_default_fallback"
    enable_fallback_prediction: true